from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtNewStyleWindow(object):
    def setupUi(self, QtNewStyleWindow):
        QtNewStyleWindow.setObjectName("QtNewStyleWindow")
        QtNewStyleWindow.resize(690, 747)
        self.centralwidget = QtWidgets.QWidget(QtNewStyleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 661, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.style_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.style_name.setObjectName("style_name")
        self.verticalLayout_3.addWidget(self.style_name)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.font = QtWidgets.QFontComboBox(self.layoutWidget)
        self.font.setObjectName("font")
        self.horizontalLayout_2.addWidget(self.font)
        self.font_size = QtWidgets.QComboBox(self.layoutWidget)
        self.font_size.setObjectName("font_size")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.font_size.addItem("")
        self.horizontalLayout_2.addWidget(self.font_size)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bold = QtWidgets.QPushButton(self.layoutWidget)
        self.bold.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bold.setIcon(icon)
        self.bold.setIconSize(QtCore.QSize(15, 15))
        self.bold.setObjectName("bold")
        self.horizontalLayout.addWidget(self.bold)
        self.italic = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.italic.setFont(font)
        self.italic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italic.setIcon(icon1)
        self.italic.setIconSize(QtCore.QSize(15, 15))
        self.italic.setObjectName("italic")
        self.horizontalLayout.addWidget(self.italic)
        self.underlined = QtWidgets.QPushButton(self.layoutWidget)
        self.underlined.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/underlined.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlined.setIcon(icon2)
        self.underlined.setIconSize(QtCore.QSize(15, 15))
        self.underlined.setObjectName("underlined")
        self.horizontalLayout.addWidget(self.underlined)
        self.text_color = QtWidgets.QPushButton(self.layoutWidget)
        self.text_color.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.text_color.setIcon(icon3)
        self.text_color.setIconSize(QtCore.QSize(20, 20))
        self.text_color.setObjectName("text_color")
        self.horizontalLayout.addWidget(self.text_color)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bold_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.bold_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/interval.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bold_2.setIcon(icon4)
        self.bold_2.setIconSize(QtCore.QSize(20, 20))
        self.bold_2.setObjectName("bold_2")
        self.horizontalLayout_3.addWidget(self.bold_2)
        self.line_spacing = QtWidgets.QComboBox(self.layoutWidget)
        self.line_spacing.setObjectName("line_spacing")
        self.line_spacing.addItem("")
        self.line_spacing.addItem("")
        self.line_spacing.addItem("")
        self.line_spacing.addItem("")
        self.line_spacing.addItem("")
        self.line_spacing.addItem("")
        self.horizontalLayout_3.addWidget(self.line_spacing)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reduce_indentation = QtWidgets.QPushButton(self.layoutWidget)
        self.reduce_indentation.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/reduce_indentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reduce_indentation.setIcon(icon5)
        self.reduce_indentation.setIconSize(QtCore.QSize(20, 20))
        self.reduce_indentation.setObjectName("reduce_indentation")
        self.horizontalLayout_4.addWidget(self.reduce_indentation)
        self.increase_indentation = QtWidgets.QPushButton(self.layoutWidget)
        self.increase_indentation.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image/increase_indentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.increase_indentation.setIcon(icon6)
        self.increase_indentation.setIconSize(QtCore.QSize(20, 20))
        self.increase_indentation.setObjectName("increase_indentation")
        self.horizontalLayout_4.addWidget(self.increase_indentation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.text_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.text_edit.setObjectName("text_edit")
        self.verticalLayout_6.addWidget(self.text_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(560, 700, 113, 32))
        self.save.setObjectName("save")
        self.esc = QtWidgets.QPushButton(self.centralwidget)
        self.esc.setGeometry(QtCore.QRect(10, 700, 113, 32))
        self.esc.setObjectName("esc")

        self.retranslateUi(QtNewStyleWindow)
        QtCore.QMetaObject.connectSlotsByName(QtNewStyleWindow)

    def retranslateUi(self, QtNewStyleWindow):
        _translate = QtCore.QCoreApplication.translate
        QtNewStyleWindow.setWindowTitle(_translate("color", "NewStyle"))
        self.label.setText(_translate("color", "Имя"))
        self.font_size.setItemText(0, _translate("color", "8"))
        self.font_size.setItemText(1, _translate("color", "9"))
        self.font_size.setItemText(2, _translate("color", "10"))
        self.font_size.setItemText(3, _translate("color", "11"))
        self.font_size.setItemText(4, _translate("color", "12"))
        self.font_size.setItemText(5, _translate("color", "14"))
        self.font_size.setItemText(6, _translate("color", "16"))
        self.font_size.setItemText(7, _translate("color", "18"))
        self.font_size.setItemText(8, _translate("color", "20"))
        self.font_size.setItemText(9, _translate("color", "22"))
        self.font_size.setItemText(10, _translate("color", "24"))
        self.font_size.setItemText(11, _translate("color", "26"))
        self.font_size.setItemText(12, _translate("color", "28"))
        self.font_size.setItemText(13, _translate("color", "36"))
        self.font_size.setItemText(14, _translate("color", "48"))
        self.font_size.setItemText(15, _translate("color", "72"))
        self.line_spacing.setItemText(0, _translate("color", "1.0"))
        self.line_spacing.setItemText(1, _translate("color", "1.15"))
        self.line_spacing.setItemText(2, _translate("color", "1.5"))
        self.line_spacing.setItemText(3, _translate("color", "2.0"))
        self.line_spacing.setItemText(4, _translate("color", "2.5"))
        self.line_spacing.setItemText(5, _translate("color", "3.0"))
        self.save.setText(_translate("color", "Сохранить"))
        self.esc.setText(_translate("color", "Отмена"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QtNewStyleWindow = QtWidgets.QWidget()
    ui = Ui_QtNewStyleWindow()
    ui.setupUi(QtNewStyleWindow)
    QtNewStyleWindow.show()
    sys.exit(app.exec_())
