from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 408)
        self.right = QtWidgets.QPushButton(Form)
        self.right.setGeometry(QtCore.QRect(420, 230, 51, 32))
        self.right.setObjectName("right")
        self.left = QtWidgets.QPushButton(Form)
        self.left.setGeometry(QtCore.QRect(20, 230, 51, 32))
        self.left.setObjectName("left")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(20, 260, 441, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 270, 211, 130))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.save = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.save.setMinimumSize(QtCore.QSize(87, 32))
        self.save.setText("")
        self.save.setObjectName("save")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/paste.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.save.setIcon(icon3)
        self.gridLayout_2.addWidget(self.save, 3, 0, 1, 1)
        self.clean = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.clean.setText("")
        self.clean.setObjectName("clean")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/clean.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.clean.setIcon(icon2)
        self.gridLayout_2.addWidget(self.clean, 2, 0, 1, 1)
        self.new_style = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.new_style.setText("")
        self.new_style.setObjectName("new_style")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/add.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.new_style.setIcon(icon1)
        self.gridLayout_2.addWidget(self.new_style, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 456, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.style3 = QtWidgets.QVBoxLayout()
        self.style3.setObjectName("style3")
        self.paste_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_12.setText("")
        self.paste_12.setIconSize(QtCore.QSize(60, 60))
        self.paste_12.setObjectName("paste_12")
        self.StylesGroup = QtWidgets.QButtonGroup(Form)
        self.StylesGroup.setObjectName("StylesGroup")
        self.StylesGroup.addButton(self.paste_12)
        self.style3.addWidget(self.paste_12)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.style3.addWidget(self.label_13)
        self.gridLayout.addLayout(self.style3, 0, 2, 1, 1)
        self.style6 = QtWidgets.QVBoxLayout()
        self.style6.setObjectName("style6")
        self.paste_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_8.setText("")
        self.paste_8.setIconSize(QtCore.QSize(60, 60))
        self.paste_8.setObjectName("paste_8")
        self.StylesGroup.addButton(self.paste_8)
        self.style6.addWidget(self.paste_8)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.style6.addWidget(self.label_9)
        self.gridLayout.addLayout(self.style6, 1, 1, 1, 1)
        self.style2 = QtWidgets.QVBoxLayout()
        self.style2.setObjectName("style2")
        self.paste_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_7.setText("")
        self.paste_7.setIconSize(QtCore.QSize(60, 60))
        self.paste_7.setObjectName("paste_7")
        self.StylesGroup.addButton(self.paste_7)
        self.style2.addWidget(self.paste_7)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.style2.addWidget(self.label_8)
        self.gridLayout.addLayout(self.style2, 0, 1, 1, 1)
        self.style8 = QtWidgets.QVBoxLayout()
        self.style8.setObjectName("style8")
        self.paste_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_11.setText("")
        self.paste_11.setIconSize(QtCore.QSize(60, 60))
        self.paste_11.setObjectName("paste_11")
        self.StylesGroup.addButton(self.paste_11)
        self.style8.addWidget(self.paste_11)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.style8.addWidget(self.label_12)
        self.gridLayout.addLayout(self.style8, 1, 3, 1, 1)
        self.style5 = QtWidgets.QVBoxLayout()
        self.style5.setObjectName("style5")
        self.paste_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_9.setText("")
        self.paste_9.setIconSize(QtCore.QSize(60, 60))
        self.paste_9.setObjectName("paste_9")
        self.StylesGroup.addButton(self.paste_9)
        self.style5.addWidget(self.paste_9)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.style5.addWidget(self.label_10)
        self.gridLayout.addLayout(self.style5, 1, 0, 1, 1)
        self.style1 = QtWidgets.QVBoxLayout()
        self.style1.setObjectName("style1")
        self.paste_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_6.setText("")
        self.paste_6.setIconSize(QtCore.QSize(60, 60))
        self.paste_6.setObjectName("paste_6")
        self.StylesGroup.addButton(self.paste_6)
        self.style1.addWidget(self.paste_6)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.style1.addWidget(self.label_5)
        self.gridLayout.addLayout(self.style1, 0, 0, 1, 1)
        self.style4 = QtWidgets.QVBoxLayout()
        self.style4.setObjectName("style4")
        self.paste_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_14.setText("")
        self.paste_14.setIconSize(QtCore.QSize(60, 60))
        self.paste_14.setObjectName("paste_14")
        self.StylesGroup.addButton(self.paste_14)
        self.style4.addWidget(self.paste_14)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.style4.addWidget(self.label_15)
        self.gridLayout.addLayout(self.style4, 0, 3, 1, 1)
        self.style7 = QtWidgets.QVBoxLayout()
        self.style7.setObjectName("style7")
        self.paste_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.paste_10.setText("")
        self.paste_10.setIconSize(QtCore.QSize(60, 60))
        self.paste_10.setObjectName("paste_10")
        self.StylesGroup.addButton(self.paste_10)
        self.style7.addWidget(self.paste_10)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.style7.addWidget(self.label_11)
        self.gridLayout.addLayout(self.style7, 1, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 400, 106, 99))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.paste_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.paste_4.setText("")
        self.paste_4.setIconSize(QtCore.QSize(60, 60))
        self.paste_4.setObjectName("paste_4")
        self.verticalLayout_5.addWidget(self.paste_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Style"))
        self.right.setText(_translate("Form", ">"))
        self.left.setText(_translate("Form", "<"))
        self.label.setText(_translate("Form", "Создать стиль"))
        self.label_2.setText(_translate("Form", "Очистить формат"))
        self.label_3.setText(_translate("Form", "Применить стили "))
        self.label_6.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
